let categoriesArray=[


   {
      id:1,
      category: "cabriolet",
      brand:"porsche",
      name:"carrera",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'88000',
      rate:3.9,
      image:("content/assets/images/products/porche-carrera.jpg"),
      numbersOfUnits:1,
   },
   {
      id:2,
      category: "Hatchback",
      brand:"ford",
      name:"focus",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'58000',
      rate:3.9,
      image:("content/assets/images/products/ford-focus-hatchback.webp"),
      numbersOfUnits:1,
   },
   {
      id:3,
      category: "Hatchback",
      brand:"kia",
      name:"ev-6",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'34000',
      rate:3.9,
      image:("content/assets/images/products/kia-ev6-hatchback.webp"),
      numbersOfUnits:1,
   },
   {
      id:4,
      category: "Sedan",
      brand:"BMW",
      name:"320i",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'68000',
      rate:3.9,
      image:("content/assets/images/products/bmw-320i.jpg"),
      numbersOfUnits:1,
   },
   {
      id:5,
      category: "Sedan",
      brand:"audi",
      name:"rs",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'88000',
      rate:3.9,
      image:("content/assets/images/products/audi-rs-sedan.webp"),
      numbersOfUnits:1,
   },
   {
      id:6,
      category: "Sedan",
      brand:"dodge",
      name:"charger",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/dodge-charger.jpg"),
      numbersOfUnits:1,
   },
   {
      id:7,
      category: "Sedan",
      brand:"honda",
      name:"civic-type-R",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'77000',
      rate:3.9,
      image:("content/assets/images/products/honda-civic-type-r.jpg"),
      numbersOfUnits:1,
   },
   {
      id:8,
      category: "Sedan",
      brand:"hyundai",
      name:"elentra-cn7",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'66000',
      rate:3.9,
      image:("content/assets/images/products/hyundai-elantra.webp"),
      numbersOfUnits:1,
   },
   {
      id:9,
      category: "Sedan",
      brand:"kia",
      name:"cerato",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'41000',
      rate:3.9,
      image:("content/assets/images/products/kia-cerato.webp"),
      numbersOfUnits:1,
   },
   {
      id:10,
      category: "Sedan",
      brand:"kia",
      name:"fortte",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'39000',
      rate:3.9,
      image:("content/assets/images/products/kia-forte-sedan.webp"),
      numbersOfUnits:1,
   },
   {
      id:11,
      category: "Sedan",
      brand:"mercedes",
      name:"cla180",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'83000',
      rate:3.9,
      image:("content/assets/images/products/mercedes-cla180-sedan.jpg"),
      numbersOfUnits:1,
   },
   {
      id:12,
      category: "Sedan",
      brand:"mercedes",
      name:"e-class",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'72000',
      rate:3.9,
      image:("content/assets/images/products/mercedes-eclass.jpg"),
      numbersOfUnits:1,
   },
   {
      id:13,
      category: "Sedan",
      brand:"mg",
      name:"5",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'50000',
      rate:3.9,
      image:("content/assets/images/products/mg5-sedan.webp"),
      numbersOfUnits:1,
   },
   {
      id:14,
      category: "Sedan",
      brand:"skoda",
      name:"superb",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:95000,
      rate:3.9,
      image:("content/assets/images/products/skoda-superb.jpg"),
      numbersOfUnits:1,
   },
   {
      id:15,
      category: "Sedan",
      brand:"toyota",
      name:"corolla",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:60000,
      rate:3.9,
      image:("content/assets/images/products/toyota-corolla.webp"),
      numbersOfUnits:1,
   },
   {
      id:16,
      category: "SUV",
      brand:"bmw",
      name:"x4",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/bmw-x4.webp"),
      numbersOfUnits:1,
   },
   {
      id:17,
      category: "SUV",
      brand:"honda",
      name:"h-rv",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'78000',
      rate:3.9,
      image:("content/assets/images/products/honda-hrv-suv.jpg"),
      numbersOfUnits:1,
   },
   {
      id:18,
      category: "SUV",
      brand:"mercedes",
      name:"g-class",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/g-class.jpg"),
      numbersOfUnits:1,
   },
   {
      id:19,
      category: "SUV",
      brand:"hyundai",
      name:"tucson",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'78000',
      rate:3.9,
      image:("content/assets/images/products/hyundai-tucson.jpg"),
      numbersOfUnits:1,
   },
   {
      id:20,
      category: "SUV",
      brand:"jeeb",
      name:"grand-cherokee",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'100000',
      rate:3.9,
      image:("content/assets/images/products/jeeb-grand-cherokee.webp"),
      numbersOfUnits:1,
   },
   {
      id:21,
      category: "SUV",
      brand:"jeeb",
      name:"compass",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'100000',
      rate:3.9,
      image:("content/assets/images/products/jeep-compass.webp"),
      numbersOfUnits:1,
   },
   {
      id:22,
      category: "SUV",
      brand:"kia",
      name:"soul",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'66000',
      rate:3.9,
      image:("content/assets/images/products/kia-soul-suv.jpg"),
      numbersOfUnits:1,
   },
   {
      id:23,
      category: "SUV",
      brand:"lexus",
      name:"lx",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'100000',
      rate:3.9,
      image:("content/assets/images/products/lexus-lx-suv.jpg"),
      numbersOfUnits:1,
   },
   {
      id:24,
      category: "SUV",
      brand:"mg",
      name:"hs",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'66000',
      rate:3.9,
      image:("content/assets/images/products/mg-hs.jpg"),
      numbersOfUnits:1,
   },
   {
      id:25,
      category: "SUV",
      brand:"peugeot",
      name:"3008",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'90000',
      rate:3.9,
      image:("content/assets/images/products/peugeot-3008.jpg"),
      numbersOfUnits:1,
   },
   {
      id:26,
      category: "SUV",
      brand:"jeeb",
      name:"wranglar",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'95000',
      rate:3.9,
      image:("content/assets/images/products/ranglar.jpg"),
      numbersOfUnits:1,
   },
   {
      id:27,
      category: "coupe",
      brand:"Chevrolet",
      name:"camaro",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'100000',
      rate:3.9,
      image:("content/assets/images/products/camaro-coupe.jpg"),
      numbersOfUnits:1,
   },
   {
      id:28,
      category: "coupe",
      brand:"dodge",
      name:"challenger",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'100000',
      rate:3.9,
      image:("content/assets/images/products/dodge-challenger.webp"),
      numbersOfUnits:1,
   },
   {
      id:29,
      category: "coupe",
      brand:"ford",
      name:"mustang",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'120000',
      rate:3.9,
      image:("content/assets/images/products/ford-mustang.webp"),
      numbersOfUnits:1,
   },
   {
      id:30,
      category: "coupe",
      brand:"nissan",
      name:"z",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'70000',
      rate:3.9,
      image:("content/assets/images/products/nissan-z-coupe.webp"),
      numbersOfUnits:1,
   },
   {
      id:31,
      category: "cabriolet",
      brand:"bmw",
      name:"m4",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/bmw-m4-caborliet.webp"),
      numbersOfUnits:1,
   },
   {
      id:32,
      category: "cabriolet",
      brand:"porche",
      name:"carrera1",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/porche-carrera.jpg"),
      numbersOfUnits:1,
   },
   {
      id:33,
      category: "SUV",
      brand:"toyota",
      name:"chr",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/toyota-chr-suv.jpeg"),
      numbersOfUnits:1,
   },
   {
      id:34,
      category: "pickup",
      brand:"dodge",
      name:"ram",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/dodge-ram.webp"),
      numbersOfUnits:1,
   },
   {
      id:35,
      category: "pickup",
      brand:"ford",
      name:"f150",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/ford-f150-pickup.webp"),
      numbersOfUnits:1,
   },
   {
      id:36,
      category: "pickup",
      brand:"ford",
      name:"ranger",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/ford-ranger-pickup.webp"),
      numbersOfUnits:1,
   },
   {
      id:37,
      category: "pickup",
      brand:"toyota",
      name:"hilux",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'98000',
      rate:3.9,
      image:("content/assets/images/products/toyota-hilux-pickup.jpg"),
      numbersOfUnits:1,
   },
   {
      id:38,
      category: "SUV",
      brand:"chevrolet",
      name:"colorado",
      description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
      price:'36000',
      rate:3.9,
      image:("content/assets/images/products/chevrolet-colorado.jpg"),
      numbersOfUnits:1,
   }
]

let accessoriesItemsArr = [
{
   id:100,
   name:"cryo-brake",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
   price: "100",
   image:("content/assets/images/accssesories/cryo-brake.jpg"),
   rate:3.9,
   numbersOfUnits:1,
},
{
   id:102,
   name:"drilled-brake-rotor",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
   price: "80",
   image:("content/assets/images/accssesories/drilled-brake-rotor.jpg"),
   rate:3.5,
   numbersOfUnits:1,
},
{
   id:103,
   name:"car-meter",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
   price: "120",
   image:("content/assets/images/accssesories/o.jpg"),
   rate:3.5,
   numbersOfUnits:1,
},
{
   id:104,
   name:"ninja-rims-r20",
   description: "Pellentesque habitant netus et malesuada fames ac turpis egestas.",
   price: "2300",
   image:("content/assets/images/accssesories/ninja-rims-r20.jpg"),
   rate:3.5,
   numbersOfUnits:1,
},
{
   id:105,
   name:"kenwood sound",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "480",
   image:("content/assets/images/accssesories/kenwood-sound.jpg"),
   rate:4.5,
   numbersOfUnits:1,
},
{
   id:106,
   name:"takeda-air-intake",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "280",
   image:("content/assets/images/accssesories/takeda-air-intake.jpg"),
   rate:4.5,
   numbersOfUnits:1,
},
{
   id:107,
   name:"ultimax-slotted-rotors",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "280",
   image:("content/assets/images/accssesories/ultimax-slotted-rotors.jpg"),
   rate:4,
   numbersOfUnits:1,
},
{
   id:108,
   name:"wolo-backup-alarm",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "120",
   image:("content/assets/images/accssesories/wolo-backup-alarm.jpg"),
   rate:4,
   numbersOfUnits:1,
},
{
   id:109,
   name:"oil-fillter",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "10",
   image:("content/assets/images/accssesories/oil-fillter.jpg"),
   rate:4,
   numbersOfUnits:1,
},
{
   id:110,
   name:"pirelli-tires-r20",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "150",
   image:("content/assets/images/accssesories/pirelli-tires-r20.jpg"),
   rate:4,
   numbersOfUnits:1,
},
{
   id:111,
   name:"sport-steering-wheel",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "120",
   image:("content/assets/images/accssesories/sport-steering-wheel.jpg"),
   rate:4.2,
   numbersOfUnits:1,
},
{
   id:112,
   name:"air-fillter",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "21",
   image:("content/assets/images/accssesories/air-fillter.jpg"),
   rate:4.7,
   numbersOfUnits:1,
},
{
   id:113,
   name:"brembo sport breakes",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "2100",
   image:("content/assets/images/accssesories/cryo-brake.jpg"),
   rate:4.7,
   numbersOfUnits:1,
},
{
   id:114,
   name:"usb air compressor",
   description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
   price: "170",
   image:("content/assets/images/accssesories/usb-air-compressor.jpg"),
   rate:5,
   numbersOfUnits:1,
},
]


localStorage.setItem('carProducts',JSON.stringify(categoriesArray))

localStorage.setItem('accessories',JSON.stringify(accessoriesItemsArr))